### ISSUE TITLE
V7, master/details competely off sync comparing to v5

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#281]
![Screenshot from 2023-11-24 12-06-59](https://github.com/jam-py/jam-py/assets/9026100/55b7295b-c981-4748-99e0-7d77ab02b5d5)
![Screenshot from 2023-11-24 12-08-28](https://github.com/jam-py/jam-py/assets/9026100/aaae0041-a750-4231-ab56-c7c62f0335af)
![Screenshot from 2023-11-24 12-03-46](https://github.com/jam-py/jam-py/assets/9026100/34650bf4-4039-4048-8c43-bdeab361a761)
![Screenshot from 2023-11-24 12-03-32](https://github.com/jam-py/jam-py/assets/9026100/cb52cdf5-46f2-4466-bb28-06dd37d2a573)

**Comment by platipusica** [comment]
Please also note the time spent - 25.6 hours and 56137.3!
Something is definitely off.

**Comment by jam-py** [comment]
Hi, Drazen.
Unfortunately, it's not at all clear what you mean

пт, 24 нояб. 2023 г. в 07:14, platipusica ***@***.***>:

**Comment by platipusica** [comment]
HI Andrew, 

in addition, pls have a look at v5 and v7 simple Master/Detail view for the same Client table:


![Screenshot from 2023-11-24 11-58-44](https://github.com/jam-py/jam-py/assets/9026100/cf4a9e60-38e5-433b-aeb3-b77f41e85462)

![Screenshot from 2023-11-24 11-57-56](https://github.com/jam-py/jam-py/assets/9026100/8537503f-b226-4a15-90c8-cd0c5d35b7cd)

**Comment by jam-py** [comment]
I am sorry but I don't understand the problem.

вт, 28 нояб. 2023 г. в 04:34, platipusica ***@***.***>:

**Comment by platipusica** [comment]
Ok, 
so what do I need to provide as more evidence that  Detail on v7 are completely wrong after the project is started with v7?

**Comment by platipusica** [comment]
bbb

**Comment by platipusica** [comment]
Here is a video, same data, nothing changed in the database:

https://github.com/jam-py/jam-py/assets/9026100/82e47a50-4d18-4026-951a-cf79bff8f041

**Comment by jam-py** [comment]
I fixed the bug.
Thank you for informing me.
Unfortunately, I didn't immediately recognize the problem


пт, 8 дек. 2023 г. в 17:55, Andrew Yushev ***@***.***>:

**Comment by platipusica** [comment]
Thanks, but everything is exactly the same. Installed:
```
Installing collected packages: jam.py
    Running setup.py install for jam.py ... done
Successfully installed jam.py-7.0.27
```

Did you try the Export and the DB I sent you the link for?

**Comment by platipusica** [comment]
Just to clarify, pls look at the DETAILS on above for v7! They are wrong, since ALL records are showing as detail  for EACH master record. That master record is not even displaying on Details v7!
This is why summary of **56137.3** HOURS are showing for one single record Case_number - 2011-433 in CASES table.

And in v5, that summary is 25.6 hours.

**Comment by jam-py** [comment]
Links that you sent me don't work.
I checked the details and it seems that they work ok.
The problem can be in how you set up details in v7.

пн, 11 дек. 2023 г. в 05:51, platipusica ***@***.***>:

**Comment by platipusica** [comment]
https://github.com/jam-py/jam-py/assets/9026100/8fac021a-14aa-4c1e-8150-ed6d16b7b5d4

**Comment by platipusica** [comment]
I did not set anything in v7 Andrew, I simply added index.html and templates.html and started the App.

To help you I sent you the link to v5 zip.
Plus,  here is the video how v7 was started.

**Comment by jam-py** [comment]
Drazen, please send me the link to v5 zip.

вт, 12 дек. 2023 г. в 04:14, platipusica ***@***.***>:

**Comment by jam-py** [comment]
I found the zip file, thanks

вт, 12 дек. 2023 г. в 04:14, platipusica ***@***.***>:

**Comment by jam-py** [comment]
I found the problem. I am trying to solve it.

ср, 13 дек. 2023 г. в 20:18, Andrew Yushev ***@***.***>:

**Comment by jam-py** [comment]
The bug is fixed now.

ср, 13 дек. 2023 г. в 20:36, Andrew Yushev ***@***.***>:

**Comment by ddavidebor** [comment]
Hey, I love that theme, any chance you could share the CSS?

**Comment by platipusica** [comment]
Both themes are in the builder for v5 and v7, no custom css.

**Comment by platipusica** [comment]
https://resourcingandbilling.pythonanywhere.com/


Try a mobile device :)

**Comment by platipusica** [comment]
Hi Andrew, 

the details are ok now, however this is still showing (on Clients):

![Screenshot from 2023-11-24 11-57-56](https://github.com/jam-py/jam-py/assets/9026100/8537503f-b226-4a15-90c8-cd0c5d35b7cd)

**Comment by platipusica** [comment]
This is how it looks from the mobile device:

**Comment by platipusica** [comment]
![mobile](https://github.com/jam-py/jam-py/assets/9026100/3b64dec2-368a-4ae7-866f-ca596e88d520)

**Comment by platipusica** [comment]
![mobile](https://github.com/jam-py/jam-py/assets/9026100/3af0a7b1-f157-4af1-9aaa-9f281e40fc8c)
